### PR TITLE
Strip quotes from title tag when creating new post with org mode

### PR DESCRIPTION
**Pull request by anachronic**
Fixes kuanyui/hexo.el#19

### CODE REVIEW

**Comment by kuanyui** [comment]
So, are you sure this will be ok in hexo + org-renderer? For example:
```
#+TITLE: ##Hello World!##
#+TITLE: [Emacs] How to Use Hexo In Emacs
#+TITLE: This Is A "Simple" Title Test
#+TITLE: What Happened When Title Contains "Double Quotes" And 'Single Quotes'?
```

**Comment by anachronic** [comment]
I believe this is more valuable than words
http://imgur.com/a/9VoPb

**Comment by kuanyui** [comment]
Ok, thanks for your testing!

**Comment by anachronic** [comment]
Thanks for merging!

**Pull request merged**
